### ISSUE TITLE
Custom form autoresponder not sending in Xperience by Kentico 29.7.1

### ISSUE THREAD

**Issue by mkayan-wakefly** [benquinlan-07/xperience-community-form-notifications#1]
I installed xperience-community-form-notifications on Xperience by Kentico 29.7.1.

I then added new emails to a form.
Under the form's new "Emails" tab, I specified both an autoresponder and a notification email.

The built-in XbyK autoresponder functionality is still visible under the "Autoresponder" tab and working.

After submitting the form, the new Notification email is sent successfully.
The new autoresponder email is not sent.

Whether or not the form's built-in XbyK autoresponder email is active makes no difference, and I see nothing in the Kentico event log.

![image](https://github.com/user-attachments/assets/8841dadc-5cfb-4e33-8b83-c97bee7e8c4f)

**Comment by benquinlan-07** [comment]
Thanks for the feedback. I have traced the issue back to be the result of the contact mapping that I was attempting to leverage to have the autoresponder function similarly to how the built in one does. This has proven unreliable with regards to when the mapping occurs, if set at all.

I have just pushed an update to the package (v1.2.0) that instead has an additional field on the autoresponder configuration in the above screenshot that allows for the selection of the Email field from the source form fields. This is more in line with the implementations from K13 and should resolve your issue.

Please let me know, after updating, if you still have further issues.

**Comment by mkayan-wakefly** [comment]
Thank you - that change is working for me.
The ability to select a specific form field as the source for the email address is a bonus.

The only issue I see is that the new `AutoresponderRecipientEmailField` field's explanation text, "Defaults to selected email subject if not specified", was copied from the `AutoresponderSubject` field and should be changed or removed.
https://github.com/benquinlan-07/xperience-community-form-notifications/blob/main/src/XperienceCommunity.FormNotifications/UI/FormNotificationEditPage.cs#L149

**Comment by benquinlan-07** [comment]
Oh damn. I must have looked at that a dozen times thinking to myself that I need to update the text. I will push an update shortly for that text.
